train: /Users/pawankumar/Hack_Aura/datasets/training
val: /Users/pawankumar/Hack_Aura/datasets/validation
test: /Users/pawankumar/Hack_Aura/datasets/testing
nc: 7
names: ['OxygenTank', 'NitrogenTank', 'FirstAidBox', 'FireAlarm', 'SafetySwitchPanel', 'EmergencyPhone', 'FireExtinguisher']                                         